version: '2'
services:
  integration:
    build: ./config/integration-test/image
    volumes:
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./config/php/ext-xdebug.ini:/usr/local/etc/php/conf.d/ext-xdebug.ini
    volumes_from:
      - appdata
    env_file: .env
    user: www-data
    networks:
      - back
    depends_on:
      - mysql
